x24_blog/config/routes.rb
X24Blog::Application.routes.draw do
  get "messages/create"
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :blogs do
    resources :posts do
      resources :messages
    end
  end

  match "/signup",  :to => 'users#new', :via=> [:get, :post]
  match "/signin",  :to => 'sessions#new', :via=> [:get, :post]
  match "/signout", :to => 'sessions#destroy', :via=> [:get, :post]

end

x24_blog/app/models/blog.rb
class Blog < ActiveRecord::Base
	attr_accessible :title, :description

	has_many :users, :through => :owners
	has_many :posts, :dependent => :destroy
	has_many :owners, :dependent => :destroy

	validates :title, :description, :presence => true
	validates :title, :length => { :minimum => 6}
	validates :description, :length => { :minimum => 15}
end

x24_blog/app/models/message.rb
class Message < ActiveRecord::Base
	attr_accessible :user_id, :message

 	belongs_to :post
 	belongs_to :user

 	has_many :users

  	validates :message,  :presence => true
end

x24_blog/app/models/owner.rb
class Owner < ActiveRecord::Base	
	attr_accessible :user_id, :blog_id
	
 	belongs_to :user
 	belongs_to :blog
end

x24_blog/app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :user_id, :title, :content
  	
  	belongs_to :blog
 	belongs_to :user

 	has_many :users
 	has_many :blogs
 	has_many :messages, :dependent => :destroy
 	
 	validates :title, :content, :presence => true

end

x24_blog/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :email_address, :password
	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	has_many :blogs, :through => :owners
	has_many :posts, :dependent => :destroy
	has_many :messages, :dependent => :destroy
	has_many :owners, :dependent => :destroy

	validates 	:name,		:presence 	=> true,
  				:length		            => { :maximum => 50 }

 	validates	:email_address,		:presence	=> true,
  				:format		            => { :with => email_regex },
           		:uniqueness 	        => { :case_sensitive => false }

    validates 	:password, 	:presence => true,
  	   			:confirmation 	      => true,
  					:length			  => { :within => 6..40 }

  	# class method that checks whether the user's email and submitted_password are valid
	def self.authenticate(email, submitted_password)
	    user = find_by_email_address(email)

	    return nil if user.nil?
	    return user if user.password == submitted_password
	end				
end

x24_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  include SessionsHelper
end

x24_blog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  	if current_user
  		@blogs = Blog.order('id DESC').all
   	 	@blog = Blog.new
  	elsif 
  		redirect_to '/signin'		
  	end
  end

  def create
  	@blog = Blog.new(params[:blog])
  	
    if @blog.save
      	flash[:success] = "#{@blog.title} is now added!"
  		@owner = Owner.new(:user_id => current_user.id, :blog_id => @blog.id).save
    elsif 
     	flash[:error] = @blog.errors.full_messages
    end

    redirect_to blogs_path
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to blogs_path
  end
end

x24_blog/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
  	@message = Post.find(params[:post_id]).messages.new(params[:message])
    @message.user_id = current_user.id

    if @message.save
      flash[:success] = "Message has been added!"
    elsif 
      flash[:error] = @message.errors.full_messages
    end

    redirect_to blog_path(params[:blog_id])
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to blog_path(params[:blog_id])
  end
end

x24_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  	@post = Blog.find(params[:blog_id]).posts.new(params[:post])
    @post.user_id = current_user.id

    if @post.save
      flash[:success] = "Post has been added!"
    elsif 
      flash[:error] = @post.errors.full_messages
    end

    redirect_to blog_path(@post.blog_id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to blog_path(params[:blog_id])
  end
end

x24_blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to users_path if signed_in?
  end

  def create
  	user = User.authenticate(params[:session][:email], params[:session][:password])

  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination."
  		render :new
  	else
  		sign_in user
  		redirect_to blogs_path
  	end
  end

  def destroy
  	sign_out
  	redirect_to signin_path
  end
end

x24_blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
  	@users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    #save the post data
    @user.update_attributes(params[:user])

    if @user.save
      flash[:success] = "Profile updated!"
    elsif 
      flash[:error] = "#{@user.errors.count} errors prohibited this post from being saved"
    end

    redirect_to edit_user_path
  end

  def destroy
   	@user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  def create
  	@user = User.new(params[:user])
    
    if @user.save
      flash[:success] = "#{@user.name} is now added!"
    elsif 
      flash[:error] = @user.errors.full_messages
    end

    redirect_to new_user_path
  end
end

x24_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

x24_blog/app/helpers/blogs_helper.rb
module BlogsHelper
end

x24_blog/app/helpers/messages_helper.rb
module MessagesHelper
end

x24_blog/app/helpers/posts_helper.rb
module PostsHelper
end

x24_blog/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  # setter method
  def current_user=(user)
    @current_user = user
  end

  # getter method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user 
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

x24_blog/app/helpers/users_helper.rb
module UsersHelper
end

x24_blog/app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

x24_blog/app/views/blogs/index.html.erb
<% content_for :title do %>Check all blogs<% end %>
<h1>Blogs</h1>
<%= simple_form_for @blog, :html => {:id => "add_blog"} do |f| %>
<% if flash[:success] %>
  	<p class='success message'><%= flash[:success] %></p>
<% elsif flash[:error] %>
	<% flash[:error].each do |i| %>
	 	<p class='error message'><%= i %></p>
	<% end %>
<% end %>
<%= f.input :title , wrapper_html: { class: 'form_entity' }%>
<div class="clear"></div>
<%= f.input :description, wrapper_html: { class: 'form_entity' } %>
<div class="clear"></div>
<%= f.button :submit, "Add Blog"%>
<div class="clear"></div>
<% end %>
<table id="blog_table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Description</th>
			<th>Number of posts</th>
			<th>Created by</th>
			<th>Registered Date</th>
		</tr>
	</thead>
	<tbody>
 	<% @blogs.each do |blog| %>
		<tr>
			<td><%= link_to blog.id, blog_path(blog) %></td>
			<td><%= link_to blog.title, blog_path(blog) %></td>
			<td><%= blog.description %></td>
			<td><%= blog.posts.length %></td>
			<td><%= blog.users[0].name %></td>
			<td><%= blog.created_at.strftime("%B %d, %Y") %></td>
		</tr>
	<% end %>
	</tbody>
</table>

x24_blog/app/views/blogs/show.html.erb
<% content_for :title do %><%= @blog.title  %><% end %>
<h1>
	<%= @blog.title  %>
	<%= link_to 'x', blog_path(@blog), :confirm => 'Are you sure?', :method => :delete, :class => "remove" %>
</h1>
<p class="blog_description"><%= @blog.description  %></p>
<div id="blogger">
	<p>Posted by: <%= @blog.users[0].name %></p>
	<p><%= @blog.created_at.strftime("%B %d, %Y") %></p>
</div>
<div id="posts">
	<h2>Add post</h2>
	<%= simple_form_for [@blog, Post.new], :html => {:id => "add_post"} do |f| %>
	<% if flash[:success] %>
	  	<p class='success message'><%= flash[:success] %></p>
	<% elsif flash[:error] %>
		<% flash[:error].each do |i| %>
		 	<p class='error message'><%= i %></p>
		<% end %>
	<% end %>
	<%= f.input :title , wrapper_html: { class: 'form_entity' }%>
	<div class="clear"></div>
	<%= f.input :content, as: :text, wrapper_html: { class: 'form_entity' } %>
	<div class="clear"></div>
	<%= f.button :submit, "Add Post"%>
	<div class="clear"></div>
	<% end %>
	<div class="clear"></div>

	<% @blog.posts.all(:order => "created_at desc").each do |post| %>
	<div class="post">
		<%= link_to 'x', blog_post_path(@blog.id, post.id), :confirm => 'Are you sure?', :method => :delete, :class => "remove" %>
		<div class="post_title"><%= post.title %></div>
		<div class="post_description"><%= post.content %></div>
		<div class="clear"></div>
		<div class="poster">
			<p>Posted by: <%= post.user.name %></p>
			<p><%= post.created_at.strftime("%B %d, %Y") %></p>
		</div>
		<div class="messages">
			<% post.messages.all(:order => "created_at desc").each do |message| %>
			<%= link_to 'x', blog_post_message_path(@blog.id, post.id, message.id), :confirm => 'Are you sure?', :method => :delete, :class => "remove" %>
			<div class="message">

				<%= message.message %>
			</div>
			<div class="clear"></div>
			<div class="messager">
				<p>Posted by: <%= message.user.name %></p>
				<p><%= message.created_at.strftime("%B %d, %Y") %></p>
			</div>
			<% end %>

		</div>
		<%= simple_form_for [@blog, post, Message.new], :html => {:id => "add_message"} do |f| %>
		<%= f.input_field :message, as: :text, wrapper_html: { class: 'form_entity' } %>
		<div class="clear"></div>
		<%= f.button :submit, "Add Message"%>
		<div class="clear"></div>
		<% end %>
		<div class="clear"></div>
	</div>
	<% end %>

</div>

x24_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to "Log out", '/signout', :id => "create_user" %>
	<div class="clear"></div>
<%= yield %>

</body>
</html>

x24_blog/app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

x24_blog/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

x24_blog/app/views/users/edit.html.erb
<% content_for :title do %>Update a new user<% end %>
<h1>Update user</h1>
<%= simple_form_for @user, :html => {:id => "add_user"} do |f| %>
<% if flash[:success] %>
  <p class='success message'><%= flash[:success] %></p>
<% elsif flash[:error] %>
  <p class='error message'><%= flash[:error] %></p>
<% end %>
<%= f.input :name , wrapper_html: { class: 'form_entity' }%>
<%= f.input :email_address, wrapper_html: { class: 'form_entity' } %>
<%= f.button :submit, "Update"%>
<% end %>

x24_blog/app/views/users/index.html.erb
<% content_for :title do %>Display all users<% end %>
<h1>Users</h1>
<table id="user_table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Full Name</th>
			<th>Email Address</th>
			<th>Registered Date</th>
		</tr>
	</thead>
	<tbody>
	<% @users.each do |user| %>
		<tr>
			<td><%= link_to user.id, user_path(user) %></td>
			<td><%= user.name %></td>
			<td><%= user.email_address %></td>
			<td>	
				<%= link_to "Edit",  edit_user_path(user) %>
				<%= link_to "Delete", user, :method => :delete, data:{ confirm:"Are you sure you want to delete?"} %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= link_to "Create New Record", new_user_path, :id => "create_user" %>

x24_blog/app/views/users/new.html.erb
<% content_for :title do %>Add a new user<% end %>
<h1>Sign up for a new user</h1>
<%= simple_form_for @user, :html => {:id => "add_user"} do |f| %>
<% if flash[:success] %>
 	 <p class='success message'><%= flash[:success] %></p>
<% elsif flash[:error] %>
 	<% flash[:error].each do |i| %>
	 	<p class='error message'><%= i %></p>
	<% end %>
<% end %>
<%= f.input :name , wrapper_html: { class: 'form_entity' }%>
<%= f.input :password, wrapper_html: { class: 'form_entity' } %>
<%= f.input :email_address, wrapper_html: { class: 'form_entity' } %>
<%= f.button :submit, "Register"%>
<% end %>
<%= link_to "Sign in now", new_session_path, :id => "create_user" %>

x24_blog/app/views/users/show.html.erb
<% content_for :title do %>Profile Info<% end %>
<div id="user_info">
	<div class="name">Full Name: <%= @user.name %></div>
	<div class="email">Email Address: <%= @user.email_address %></div>
	<%= link_to "Edit",  edit_user_path(@user) %>
	<%= link_to "Delete",  user_path(@user), :confirm => 'Are you sure?', :method => :delete %>
</div>